name: hello-world
on: push
jobs:
  printing:
    name: print hello world
    runs-on: ubuntu-latest
    steps:
      - name: checking out repo
        uses: actions/checkout@v4
      - run: cat hello_world.txt
